-- ============================================================
-- Migration 007: Remote Document Signing Requests
-- ============================================================
-- Allows contractors to send documents to homeowners for
-- remote e-signature. Homeowners open a unique link in their
-- browser, review the document, and sign with their finger/mouse.
-- ============================================================

CREATE TABLE IF NOT EXISTS signing_requests (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  -- Public token used in the signing URL — unguessable UUID
  token          uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  contact_id     uuid NOT NULL REFERENCES contacts(id) ON DELETE CASCADE,
  company_id     uuid NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  doc_type       text NOT NULL,
  homeowner_name  text NOT NULL DEFAULT '',
  homeowner_email text NOT NULL DEFAULT '',
  status         text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'signed', 'expired', 'saved')),
  -- Full document rendering context (addresses, dates, values, etc.)
  -- Captured at request creation so the public page renders the same doc
  document_context jsonb NOT NULL DEFAULT '{}',
  -- Optional: contractor signs first before sending
  contractor_signature_data_url text,
  -- Set by the homeowner when they complete signing
  homeowner_signature_data_url  text,
  -- Pre-signed Supabase upload URL (generated by contractor at request time)
  -- Allows the homeowner's browser to upload the signed PDF without auth
  pdf_upload_url   text,
  pdf_storage_path text,
  -- Public URL of the completed signed PDF (set after homeowner signs)
  pdf_public_url   text,
  signed_at      timestamptz,
  -- Link expires after 7 days
  expires_at     timestamptz NOT NULL DEFAULT (now() + INTERVAL '7 days'),
  created_at     timestamptz NOT NULL DEFAULT now()
);

-- ── Row-Level Security ──────────────────────────────────────
ALTER TABLE signing_requests ENABLE ROW LEVEL SECURITY;

-- Authenticated company members: full access to their own requests
CREATE POLICY "signing_requests_company_access"
  ON signing_requests
  FOR ALL
  USING (
    company_id IN (
      SELECT company_id FROM profiles WHERE id = auth.uid()
    )
  );

-- Public (anon): read any non-expired request — security via unguessable UUID token
CREATE POLICY "signing_requests_public_read"
  ON signing_requests
  FOR SELECT
  TO anon
  USING (expires_at > now());

-- Public (anon): update a pending request to signed (homeowner completing signing)
-- Only allows transitioning status from 'pending' → 'signed'
CREATE POLICY "signing_requests_public_complete"
  ON signing_requests
  FOR UPDATE
  TO anon
  USING  (status = 'pending' AND expires_at > now())
  WITH CHECK (status = 'signed');

-- ── Indexes ─────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS signing_requests_token_idx        ON signing_requests (token);
CREATE INDEX IF NOT EXISTS signing_requests_contact_id_idx   ON signing_requests (contact_id);
CREATE INDEX IF NOT EXISTS signing_requests_company_id_idx   ON signing_requests (company_id);
CREATE INDEX IF NOT EXISTS signing_requests_status_idx       ON signing_requests (status);
