default_platform(:ios)

platform :ios do

  desc "Build and upload to TestFlight"
  lane :beta do
    # Use Xcode automatic signing
    automatic_code_signing(
      path: "ios/App/App.xcodeproj",
      use_automatic_signing: true,
      team_id: "F8DF3ML3MW"
    )

    # Bump build number automatically
    increment_build_number(
      xcodeproj: "ios/App/App.xcodeproj"
    )

    # Build the app
    build_app(
      scheme: "App",
      project: "ios/App/App.xcodeproj",
      export_method: "app-store",
      xcargs: "-allowProvisioningUpdates",
      export_options: {
        signingStyle: "automatic",
        teamID: "F8DF3ML3MW"
      },
      output_directory: "./build",
      output_name: "TrussCTR.ipa",
      clean: true
    )

    # Upload to TestFlight
    upload_to_testflight(
      username: "jeffrey88newell@gmail.com",
      app_identifier: "com.restore614.trussctr",
      team_id: "F8DF3ML3MW",
      skip_waiting_for_build_processing: true
    )
  end

end
